---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-headless
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.headless.annotations }}
  annotations:
{{ toYaml .Values.headless.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.headless.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.properties.httpsPort }}
    name: https
  - port: {{ .Values.properties.clusterPort }}
    name: cluster
  - port: {{ .Values.properties.siteToSite.port }}
    name: site-to-site
  selector:
    app: {{ include "apache-nifi.name" . | quote }}
    release: {{ .Release.Name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
{{- with .Values.service.sessionAffinityConfig }}
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      name: https
      targetPort: {{ .Values.properties.httpsPort }}
      nodePort: {{ .Values.service.nodePort }}
    - port: {{ .Values.properties.siteToSite.port }}
      name: site-to-site
      targetPort: {{ .Values.properties.siteToSite.port }}
  {{- if .Values.properties.siteToSite.nodePort }}
      nodePort: {{ .Values.properties.siteToSite.nodePort }}
  {{- end }}
{{- if .Values.service.processors.enabled }}
{{- with .Values.service.processors.ports  }}
{{- range . }}
    - port: {{ .port }}
      name: {{ .name }}
      targetPort: {{ .targetPort }}
      {{- if eq $.Values.service.type "NodePort" }}
      nodePort: {{ .nodePort }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.metrics.prometheus.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apache-nifi.fullname" . }}-metrics
  labels:
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metrics.prometheus.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    app: {{ template "apache-nifi.name" . }}
    release: {{ .Release.Name }}
  type: ClusterIP
  {{- end }}    