name: Test-SingleUser

on:
  push:
  pull_request:

jobs:
  test-singleuser:
    name: Test NiFi Helm Chart Single User
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.GITHUB_TOKEN }}          
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add dysnix https://dysnix.github.io/charts/
          helm repo update
          helm dep up
      - name: Install openldap
        run: |
          kubectl apply -f tests/03-ldap
          kubectl rollout status --watch deployment/openldap --timeout=5m
      - name: Install Nifi
        run: helm install nifi .
      - name: Check deployment status
        run: |
          kubectl rollout status --watch statefulset/nifi --timeout=5m
      - name: Wait for NiFi web server to start
        run: |
          for n in [ 0 1 2 3 4 5 6 7 8 9 ]
          do
            if kubectl logs pod/nifi-0 -c app-log | grep 'JettyServer NiFi has started'
            then
              exit 0
            fi
            sleep 30
          done
          echo NiFi did not start for 300 seconds!
          exit 1
      - name: Check that singleUser login works
        run: |
          kubectl exec nifi-0 -c server -- curl -d username=username -d password=changemechangeme -sk https://localhost:8443/nifi-api/access/token | \
            grep -v 'The supplied username and password are not valid.'
      - name: Check that singleUser incorrect password fails
        run: |
          kubectl exec nifi-0 -c server -- curl -d username=username -d password=donotchangeme -sk https://localhost:8443/nifi-api/access/token | \
            grep 'The supplied username and password are not valid.'
