name: Test-SafetyValve

on:
  push:
  pull_request:

jobs:
  test-safetyvalve:
    name: Test NiFi Helm Chart SafetyValve Properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.GITHUB_TOKEN }}
      #- run: minikube addons list
      #- name: Interact with the cluster
      #  run: kubectl get nodes
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add dysnix https://dysnix.github.io/charts/
          helm repo update
          helm dep up
      - name: Install Nifi
        run: helm install nifi . -f tests/01-safetyValve-values.yaml
      - name: Check deployment status
        run: |
          kubectl rollout status --watch statefulset/nifi --timeout=5m
      - name: Wait for NiFi web server to start
        run: |
          for n in [ 0 1 2 3 4 5 6 7 8 9 ]
          do
            if kubectl logs pod/nifi-0 -c app-log | grep 'JettyServer NiFi has started'
            then
              exit 0
            fi
            sleep 30
          done
          echo NiFi did not start for 300 seconds!
          exit 1
      - name: Check safetyValve content is correct
        run: |
          NPFP=$(kubectl exec pod/nifi-0 -c server -- ps auxww | \
            awk 'BEGIN { RS = " " } /^-Dnifi.properties.file.path/ { split($0,a,"=",seps); printf("%s",a[2]) }')
          kubectl exec pod/nifi-0 -c server -- cat $NPFP
          kubectl exec pod/nifi-0 -c server -- cat $NPFP | \
            grep 'nifi.content.claim.max.appendable.size=1 B'
